let products=[];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attr=v=>String(v??'').replace(/'/g,"\\'");
function pass(){return $('#pass').value.trim()||sessionStorage.getItem('elk_admin_pass')||''}
async function api(url,options={}){const headers={...(options.headers||{}),'x-admin-password':pass()};const r=await fetch(url,{...options,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`تعذر تنفيذ الطلب (${r.status}).`);return d}
function stats(){const total=products.length, sold=products.filter(p=>p.status==='sold').length;$('#statTotal').textContent=total;$('#statAvailable').textContent=total-sold;$('#statSold').textContent=sold;$('#statImages').textContent=products.reduce((n,p)=>n+(p.images||[p.image]).filter(Boolean).length,0)}
function render(){stats();$('#adminList').innerHTML=products.map(p=>`<div class="cart-row" style="align-items:center"><div style="flex:1"><b>${esc(p.name)}</b><br><small>${Number(p.price||0).toLocaleString('ar-EG')} ج.م — ${(p.images||[p.image]).filter(Boolean).length} صور — <strong style="color:${p.status==='sold'?'#b21d1d':'#16834b'}">${p.status==='sold'?'مباعة':'متاحة'}</strong></small></div><button class="btn" onclick="editProduct('${attr(p.id)}')">تعديل</button><button class="btn" onclick="delProduct('${attr(p.id)}')">حذف</button></div>`).join('')||'<p style="color:#777">لا توجد سيارات حتى الآن.</p>'}
async function refresh(){products=await api('/api/admin/products');render()}
function showDashboard(){ $('#loginPanel').classList.add('hidden'); $('#dashboard').classList.remove('hidden'); refresh().catch(e=>{$('#loginStatus').textContent=e.message;logout()}) }
function logout(){sessionStorage.removeItem('elk_admin_pass');$('#dashboard').classList.add('hidden');$('#loginPanel').classList.remove('hidden');$('#pass').value=''}
$('#loginBtn').onclick=async()=>{const password=$('#pass').value.trim();if(!password){$('#loginStatus').textContent='اكتب كلمة المرور أولًا.';return}$('#loginBtn').disabled=true;$('#loginStatus').textContent='جاري التحقق...';try{sessionStorage.setItem('elk_admin_pass',password);await api('/api/admin/products');$('#loginStatus').textContent='';showDashboard()}catch(e){sessionStorage.removeItem('elk_admin_pass');$('#loginStatus').textContent=e.message}finally{$('#loginBtn').disabled=false}};
$('#pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});$('#logoutBtn').onclick=logout;$('#refreshBtn').onclick=()=>refresh().catch(e=>alert(e.message));
$('#resetBtn').onclick=()=>{const f=$('#productForm');f.reset();f.elements.id.value='';f.elements.status.value='available';$('#formTitle').textContent='إضافة سيارة جديدة';$('#imagePreview').innerHTML='';$('#uploadStatus').textContent=''};
window.editProduct=id=>{const p=products.find(x=>x.id===id);if(!p)return;const f=$('#productForm');['id','name','price','year','category','transmission','fuel','badge','description','status'].forEach(k=>f.elements[k].value=p[k]??'');f.elements.images.value=(p.images||[p.image]).filter(Boolean).join('\n');$('#imagePreview').innerHTML=(p.images||[p.image]).filter(Boolean).map(u=>`<img src="${esc(u)}">`).join('');$('#formTitle').textContent='تعديل بيانات السيارة';scrollTo({top:0,behavior:'smooth'})};
window.delProduct=async id=>{if(!confirm('حذف السيارة نهائيًا؟'))return;try{await api('/api/admin/products/'+encodeURIComponent(id),{method:'DELETE'});await refresh()}catch(e){alert(e.message)}};
$('#productForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/products',{method:'POST',body:new FormData(e.target)});alert('تم حفظ السيارة بنجاح');$('#resetBtn').click();await refresh()}catch(err){alert(err.message)}};
$('#imageFiles').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;const status=$('#uploadStatus'),ta=$('#productForm').elements.images,allowed=['image/jpeg','image/png','image/webp','image/gif'];if(files.some(f=>!allowed.includes(f.type))){status.textContent='مسموح فقط JPG وPNG وWEBP وGIF.';return}if(files.some(f=>f.size>2*1024*1024)){status.textContent='حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.';return}const old=ta.value.split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);let urls=[];try{for(let i=0;i<files.length;i++){status.textContent=`جاري رفع الصورة ${i+1} من ${files.length}...`;const fd=new FormData();fd.append('images',files[i]);const d=await api('/api/admin/upload-images',{method:'POST',body:fd});urls.push(...(d.urls||[]))}ta.value=[...old,...urls].join('\n');$('#imagePreview').innerHTML=ta.value.split(/\r?\n+/).filter(Boolean).map(u=>`<img src="${esc(u)}">`).join('');status.textContent=`تم رفع ${urls.length} صورة. اضغط حفظ السيارة.`;e.target.value=''}catch(err){status.textContent=err.message}});
const saved=sessionStorage.getItem('elk_admin_pass');if(saved){$('#pass').value=saved;api('/api/admin/products').then(showDashboard).catch(()=>sessionStorage.removeItem('elk_admin_pass'))}
