let products=[];let editingId=null;let sessionPass=sessionStorage.getItem('elkheshenAdminPass')||'';let adminSearch='';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const attr=v=>String(v??'').replace(/'/g,"\\'");
function setLoginError(msg){$('#loginError').textContent=msg||'';$('#loginError').classList.toggle('hidden',!msg)}
async function api(url,options={}){const headers={...(options.headers||{}),'x-admin-password':sessionPass};const r=await fetch(url,{...options,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`تعذر تنفيذ الطلب (${r.status})`);return d}
async function login(){sessionPass=$('#pass').value.trim();if(!sessionPass)return setLoginError('اكتب كلمة المرور أولًا.');try{await api('/api/admin/products');sessionStorage.setItem('elkheshenAdminPass',sessionPass);setLoginError('');$('#loginCard').style.display='none';$('#dashboard').style.display='block';await refresh()}catch(e){sessionStorage.removeItem('elkheshenAdminPass');setLoginError(e.message)}}
async function refresh(){try{products=await api('/api/admin/products');updateStats();render()}catch(e){if(e.message.includes('كلمة المرور')){sessionStorage.removeItem('elkheshenAdminPass');$('#dashboard').style.display='none';$('#loginCard').style.display='block'}else $('#adminList').innerHTML=`<div class="danger-note">${esc(e.message)}</div>`}}
function updateStats(){const sold=products.filter(p=>p.status==='sold').length;$('#statTotal').textContent=products.length;$('#statAvailable').textContent=products.length-sold;$('#statSold').textContent=sold;$('#statImages').textContent=products.reduce((n,p)=>n+(Array.isArray(p.images)?p.images.length:(p.image?1:0)),0)}
function render(){const list=products.filter(p=>`${p.name||''} ${p.year||''}`.toLowerCase().includes(adminSearch.toLowerCase()));$('#adminList').innerHTML=list.map(p=>{const imgs=Array.isArray(p.images)&&p.images.length?p.images:[p.image].filter(Boolean);return `<div class="admin-car"><img src="${esc(imgs[0]||'')}" alt=""><div class="admin-car-main"><b>${esc(p.name)}</b><p>${Number(p.price||0).toLocaleString('ar-EG')} ج.م ${p.year?'• '+esc(p.year):''}</p><div class="admin-badges"><span class="admin-badge ${p.status==='sold'?'sold':''}">${p.status==='sold'?'مباعة':'متاحة'}</span><span class="admin-badge">${imgs.length} صور</span>${p.category?`<span class="admin-badge">${esc(p.category)}</span>`:''}</div></div><div class="admin-actions"><button class="mini-btn" onclick="editProduct('${attr(p.id)}')">تعديل</button><button class="mini-btn danger" onclick="deleteProduct('${attr(p.id)}')">حذف</button></div></div>`}).join('')||'<div class="admin-empty">لا توجد سيارات مطابقة للبحث.</div>'}
function resetForm(){editingId=null;$('#editorTitle').textContent='إضافة سيارة جديدة';$('#productForm').reset();$('#productForm').elements.id.value='';$('#imagePreview').innerHTML='';$('#uploadStatus').textContent='يمكنك اختيار أكثر من صورة مرة واحدة.';$('#saveStatus').textContent='';window.scrollTo({top:0,behavior:'smooth'})}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editingId=id;const f=$('#productForm');['id','name','price','year','category','status','transmission','fuel','badge','description'].forEach(k=>f.elements[k].value=p[k]??'');f.elements.images.value=(p.images||[p.image]).filter(Boolean).join('\n');$('#editorTitle').textContent='تعديل السيارة';$('#imagePreview').innerHTML=(p.images||[p.image]).filter(Boolean).map(u=>`<img src="${esc(u)}" alt="">`).join('');$('#saveStatus').textContent='أنت تعدّل سيارة موجودة.';window.scrollTo({top:0,behavior:'smooth'})}
async function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p||!confirm(`حذف ${p.name} نهائيًا؟`))return;try{await api('/api/admin/products/'+encodeURIComponent(id),{method:'DELETE'});if(editingId===id)resetForm();await refresh()}catch(e){alert(e.message)}}
async function uploadImages(files){if(!files.length)return;const allowed=['image/jpeg','image/png','image/webp','image/gif'];if(files.some(f=>!allowed.includes(f.type)))throw new Error('مسموح فقط JPG وPNG وWEBP وGIF.');if(files.some(f=>f.size>2*1024*1024))throw new Error('حجم كل صورة يجب ألا يتجاوز 2 ميجابايت.');const current=$('#productForm').elements.images.value.split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);let urls=[];for(let i=0;i<files.length;i++){const fd=new FormData();fd.append('images',files[i]);$('#uploadStatus').textContent=`جاري رفع الصورة ${i+1} من ${files.length}...`;const d=await api('/api/admin/upload-images',{method:'POST',body:fd});urls.push(...(d.urls||[]))}$('#productForm').elements.images.value=[...current,...urls].join('\n');$('#imagePreview').innerHTML=$('#productForm').elements.images.value.split(/\r?\n+/).filter(Boolean).map(u=>`<img src="${esc(u)}" alt="">`).join('');$('#uploadStatus').textContent=`تم رفع ${urls.length} صورة بنجاح. لا تنسَ حفظ السيارة.`}
$('#loginBtn').onclick=login;$('#pass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logoutTop').onclick=()=>{sessionStorage.removeItem('elkheshenAdminPass');location.reload()};$('#refreshBtn').onclick=refresh;$('#newCarBtn').onclick=resetForm;$('#cancelEdit').onclick=resetForm;$('#adminSearch').oninput=e=>{adminSearch=e.target.value;render()};$('#imageFiles').onchange=async e=>{try{await uploadImages([...e.target.files])}catch(err){$('#uploadStatus').textContent=err.message}finally{e.target.value=''}};
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const data=Object.fromEntries(f.entries());data.images=data.images.split(/\r?\n+/).map(x=>x.trim()).filter(Boolean);if(!data.images.length)return $('#saveStatus').textContent='أضف صورة واحدة على الأقل.';$('#saveBtn').disabled=true;$('#saveStatus').textContent='جاري الحفظ...';try{await api('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});$('#saveStatus').textContent='تم الحفظ بنجاح ✓';await refresh();setTimeout(resetForm,350)}catch(err){$('#saveStatus').textContent=err.message}finally{$('#saveBtn').disabled=false}};
if(sessionPass){login()}
window.editProduct=editProduct;window.deleteProduct=deleteProduct;
