const WA='201119295523';
const FALLBACK_PRODUCTS=[
{id:'demo-mercedes-c200',name:'مرسيدس C200',price:2350000,year:'2022',category:'sedan',transmission:'أوتوماتيك',fuel:'بنزين',badge:'مميز',description:'سيارة سيدان فاخرة بتجهيزات مميزة وحالة ممتازة.',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=85']},
{id:'demo-bmw-320',name:'BMW 320',price:2100000,year:'2021',category:'sedan',transmission:'أوتوماتيك',fuel:'بنزين',badge:'فرصة',description:'BMW 320 بتصميم رياضي وتجهيزات مريحة.',image:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=85']},
{id:'demo-audi-a6',name:'Audi A6',price:2750000,year:'2023',category:'sedan',transmission:'أوتوماتيك',fuel:'بنزين',badge:'حديث',description:'Audi A6 بمظهر فاخر ومساحة داخلية مريحة.',image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1000&q=85']},
{id:'demo-tucson',name:'هيونداي توسان',price:1450000,year:'2021',category:'suv',transmission:'أوتوماتيك',fuel:'بنزين',badge:'الأكثر طلبًا',description:'SUV عملية ومناسبة للاستخدام اليومي والعائلي.',image:'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1000&q=85']}
];
let products=[];let currentFilter='all';let searchTerm='';let cart=JSON.parse(localStorage.getItem('elkheshenCart')||'[]');
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const js=v=>String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'");
function imgs(p){return [...new Set((Array.isArray(p.images)?p.images:[]).concat(p.image||[]).filter(Boolean).map(String))]}
function normalize(p){return {...p,images:imgs(p),image:p.image||imgs(p)[0]||''}}
function categoryLabel(c){return c==='suv'?'SUV':c==='sedan'?'سيدان':'أخرى'}
function formatPrice(n){return Number(n||0).toLocaleString('ar-EG')+' ج.م'}
function filtered(){return products.filter(p=>(currentFilter==='all'||(p.category||'other')===currentFilter)&&(!searchTerm||`${p.name} ${p.year||''} ${p.description||''}`.toLowerCase().includes(searchTerm.toLowerCase())))}
function render(){const list=filtered();$('#resultsCount').textContent=`${list.length} سيارة${searchTerm?' مطابقة للبحث':''}`;$('#clearSearch').classList.toggle('hidden',!searchTerm);$('#emptyState').classList.toggle('hidden',!!list.length);const grid=$('#productsGrid');if(!list.length){grid.innerHTML='';return}grid.innerHTML=list.map(card).join('')}
function card(p){const sold=p.status==='sold';const pictures=imgs(p);return `<article class="car-card-ui"><div class="car-image-wrap"><img src="${esc(pictures[0]||'')}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.opacity='.15'">${p.badge&&!sold?`<span class="car-badge">${esc(p.badge)}</span>`:''}${sold?'<span class="sold-label">مباعة</span><div class="sold-overlay">مبــــاع</div>':''}</div><div class="car-content"><h3 class="car-title">${esc(p.name)}</h3><div class="car-meta">${p.year?`<span>${esc(p.year)}</span>`:''}${p.category?`<span>${esc(categoryLabel(p.category))}</span>`:''}${p.transmission?`<span>${esc(p.transmission)}</span>`:''}</div><p class="car-desc">${esc(p.description||'للاستفسار عن الحالة والتجهيزات تواصل معنا مباشرة.')}</p><div class="car-bottom"><div class="car-price">${formatPrice(p.price)}</div><div class="car-actions"><button class="btn ${sold?'sold-btn':'btn-primary'}" ${sold?'disabled':''} onclick="${sold?'return false':`add('${js(p.id)}')`}">${sold?'مباعة':'أضف للسلة'}</button><button class="icon-action" aria-label="التفاصيل" onclick="openProduct('${js(p.id)}')">↗</button></div></div></div></article>`}
async function load(){try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d))throw new Error('invalid');products=d.map(normalize);render()}catch(e){console.warn('Products API unavailable, showing safe demo data.',e);products=FALLBACK_PRODUCTS.map(normalize);render();showToast('الموقع يعمل — بيانات السيارات الافتراضية ظاهرة مؤقتًا.');}}
function add(id){const p=products.find(x=>x.id===id);if(!p||p.status==='sold')return;const i=cart.find(x=>x.id===id);if(i)i.qty++;else cart.push({id,qty:1});saveCart();openCart();showToast('تمت إضافة السيارة للسلة');}
function saveCart(){localStorage.setItem('elkheshenCart',JSON.stringify(cart));updateCount()}function updateCount(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function openCart(){$('#cartModal').classList.remove('hidden');renderCart()}function renderCart(){const box=$('#cartItems');if(!cart.length){box.innerHTML='<div class="empty-state"><div>🛒</div><h3>السلة فارغة</h3><p>اختار سيارة وأضفها للسلة.</p></div>';$('#cartTotal').textContent='0';return}box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return'';return `<div class="cart-row"><img class="cart-thumb" src="${esc(imgs(p)[0]||'')}" alt=""><div class="cart-product-info"><b>${esc(p.name)}</b><br><small>${formatPrice(p.price)}</small></div><div class="qty"><button onclick="changeQty('${js(i.id)}',-1)">−</button>${i.qty}<button onclick="changeQty('${js(i.id)}',1)">+</button></div></div>`}).join('');$('#cartTotal').textContent=cart.reduce((n,i)=>n+i.qty,0)}
function changeQty(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();renderCart()}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const list=imgs(p);const sold=p.status==='sold';$('#productModal').innerHTML=`<div class="modal-card product-detail"><button class="close" onclick="closeProduct()">×</button><div class="detail-layout"><div><div class="detail-main"><img id="detailMainImg" src="${esc(list[0]||'')}" alt="${esc(p.name)}"></div><div class="detail-thumbs">${list.map((im,i)=>`<button class="detail-thumb ${i===0?'active':''}" onclick="showDetailImage(${i})"><img src="${esc(im)}" alt=""></button>`).join('')}</div></div><div class="detail-info"><span class="eyebrow">CAR DETAILS</span><h2>${esc(p.name)}</h2><p class="detail-desc">${esc(p.description||'تفاصيل السيارة والتجهيزات متاحة عند التواصل معنا.')}</p><div class="car-meta">${p.year?`<span>موديل ${esc(p.year)}</span>`:''}${p.category?`<span>${esc(categoryLabel(p.category))}</span>`:''}${p.transmission?`<span>${esc(p.transmission)}</span>`:''}${p.fuel?`<span>${esc(p.fuel)}</span>`:''}</div><div class="detail-price">${formatPrice(p.price)}</div>${sold?'<button class="btn sold-btn full" disabled>السيارة مباعة</button>':'<button class="btn btn-primary full" onclick="add(\''+js(p.id)+'\');closeProduct()">أضف للسلة 🛒</button>'}</div></div></div>`;$('#productModal').dataset.images=JSON.stringify(list);$('#productModal').classList.remove('hidden')}
function showDetailImage(i){const m=$('#productModal'),list=JSON.parse(m.dataset.images||'[]');if(list[i])$('#detailMainImg').src=list[i];document.querySelectorAll('.detail-thumb').forEach((b,n)=>b.classList.toggle('active',n===i))}function closeProduct(){$('#productModal').classList.add('hidden')}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),2600)}
$('#cartBtn').onclick=openCart;$('#checkoutBtn').onclick=()=>{if(!cart.length)return showToast('السلة فارغة');$('#cartModal').classList.add('hidden');$('#orderModal').classList.remove('hidden')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('#orderForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `• ${p?.name||i.id} × ${i.qty}`}).join('\n');const msg=`مرحبًا، أريد الاستفسار عن السيارات التالية من Automobile Elkheshen.\n\n${lines}\n\nالاسم: ${f.get('customer')}\nالهاتف: ${f.get('phone')}\nالعنوان: ${f.get('address')||'غير محدد'}\nملاحظات: ${f.get('note')||'لا يوجد'}`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,'_blank','noopener');cart=[];saveCart();e.target.reset();$('#orderModal').classList.add('hidden')};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});
$('#searchInput').addEventListener('input',e=>{searchTerm=e.target.value.trim();render()});$('#searchBtn').onclick=()=>$('#cars').scrollIntoView({behavior:'smooth'});$('#clearSearch').onclick=()=>{$('#searchInput').value='';searchTerm='';render()};$('#mobileMenu').onclick=()=>$('#mainNav').classList.toggle('open');document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>$('#mainNav').classList.remove('open'));$('#yearNow').textContent=new Date().getFullYear();updateCount();load();
