const express=require('express');
const multer=require('multer');
const app=express();
const upload=multer({storage:multer.memoryStorage(),limits:{files:12,fileSize:2*1024*1024}});
app.use(express.json({limit:'1mb'}));
app.use(express.urlencoded({extended:true,limit:'1mb'}));
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'';
const DEFAULT_PRODUCTS=[
{id:'mercedes-c200',name:'مرسيدس C200',price:2350000,year:'2022',category:'sedan',transmission:'أوتوماتيك',fuel:'بنزين',badge:'مميز',description:'سيارة سيدان فاخرة بتجهيزات مميزة وحالة ممتازة. تواصل معنا لمعرفة التفاصيل الكاملة.',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=85'],status:'available'},
{id:'bmw-320',name:'BMW 320',price:2100000,year:'2021',category:'sedan',transmission:'أوتوماتيك',fuel:'بنزين',badge:'فرصة',description:'BMW 320 بتصميم رياضي وتجهيزات مريحة. اسأل عن الحالة والمواصفات.',image:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1000&q=85'],status:'available'},
{id:'audi-a6',name:'Audi A6',price:2750000,year:'2023',category:'sedan',transmission:'أوتوماتيك',fuel:'بنزين',badge:'حديث',description:'Audi A6 بمظهر فاخر ومساحة داخلية مريحة. للاستفسار تواصل معنا.',image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1000&q=85'],status:'available'},
{id:'hyundai-tucson',name:'هيونداي توسان',price:1450000,year:'2021',category:'suv',transmission:'أوتوماتيك',fuel:'بنزين',badge:'الأكثر طلبًا',description:'SUV عملية ومناسبة للاستخدام اليومي والعائلي. تواصل لمعرفة التجهيزات.',image:'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1000&q=85',images:['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1000&q=85'],status:'available'}
];
function config(){return{token:process.env.GITHUB_TOKEN,repo:process.env.GITHUB_REPO,branch:process.env.GITHUB_BRANCH||'main',path:process.env.GITHUB_PRODUCTS_PATH||'data/products.json'}}
function auth(req,res,next){if(!ADMIN_PASSWORD)return res.status(500).json({error:'ADMIN_PASSWORD غير مضبوط في Vercel.'});if(req.headers['x-admin-password']!==ADMIN_PASSWORD)return res.status(401).json({error:'كلمة المرور غير صحيحة.'});next()}
async function gh(url,options={}){const c=config();if(!c.token||!c.repo)throw new Error('GITHUB_TOKEN و GITHUB_REPO غير مضبوطين في Vercel.');const r=await fetch(url,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok)throw new Error(d.message||`GitHub error ${r.status}`);return d}
function normalize(p){const images=Array.isArray(p.images)&&p.images.length?p.images.filter(Boolean).map(String):[p.image].filter(Boolean);return{...p,id:String(p.id||''),name:String(p.name||''),price:Number(p.price||0),image:String(p.image||images[0]||''),images,status:p.status==='sold'?'sold':'available'}}
async function readProducts(){const c=config();if(!c.token||!c.repo)return DEFAULT_PRODUCTS.map(normalize);const d=await gh(`https://api.github.com/repos/${c.repo}/contents/${c.path}?ref=${encodeURIComponent(c.branch)}`);const parsed=JSON.parse(Buffer.from(String(d.content).replace(/\n/g,''),'base64').toString('utf8'));if(!Array.isArray(parsed))throw new Error('ملف المنتجات في GitHub غير صالح.');return parsed.map(normalize)}
async function writeProducts(products,message){const c=config();if(!c.token||!c.repo)throw new Error('GITHUB_TOKEN و GITHUB_REPO غير مضبوطين في Vercel.');let sha=null;try{sha=(await gh(`https://api.github.com/repos/${c.repo}/contents/${c.path}?ref=${encodeURIComponent(c.branch)}`)).sha}catch(e){}const content=Buffer.from(JSON.stringify(products.map(normalize),null,2),'utf8').toString('base64');const body={message:message||'Update products',content,branch:c.branch};if(sha)body.sha=sha;return gh(`https://api.github.com/repos/${c.repo}/contents/${c.path}`,{method:'PUT',body:JSON.stringify(body)})}
function rawUrl(path){const c=config();return`https://raw.githubusercontent.com/${c.repo}/${encodeURIComponent(c.branch)}/${path.split('/').map(encodeURIComponent).join('/')}`}
async function uploadGithub(file){const c=config();if(!c.token||!c.repo)throw new Error('GITHUB_TOKEN و GITHUB_REPO غير مضبوطين في Vercel.');const ext=(file.originalname.match(/\.[a-zA-Z0-9]+$/)||['.jpg'])[0].toLowerCase();const safe=['.jpg','.jpeg','.png','.webp','.gif'].includes(ext)?ext:'.jpg';const base=String(file.originalname||'image').replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,50)||'image';const filename=`${Date.now()}-${Math.random().toString(36).slice(2,8)}-${base}${safe}`;const path=`uploads/${filename}`;await gh(`https://api.github.com/repos/${c.repo}/contents/${path}`,{method:'PUT',body:JSON.stringify({message:`Upload product image ${filename}`,content:file.buffer.toString('base64'),branch:c.branch})});return rawUrl(path)}
function cleanProduct(body,old={}){const name=String(body.name??old.name??'').trim();const price=Number(body.price??old.price??0);if(!name)throw new Error('اسم السيارة مطلوب.');if(!Number.isFinite(price)||price<0)throw new Error('السعر غير صحيح.');let images=Array.isArray(body.images)?body.images:(typeof body.images==='string'?body.images.split(/\r?\n|,/):[]);images=images.map(x=>String(x||'').trim()).filter(Boolean);if(!images.length)images=Array.isArray(old.images)?old.images.filter(Boolean):[old.image].filter(Boolean);if(!images.length)throw new Error('أضف صورة واحدة على الأقل.');const p={id:String(body.id??old.id??'').trim()||`car-${Date.now()}`,name,price,year:String(body.year??old.year??'').trim(),category:['sedan','suv','other'].includes(String(body.category??old.category??''))?String(body.category??old.category):'other',transmission:String(body.transmission??old.transmission??'').trim(),fuel:String(body.fuel??old.fuel??'').trim(),badge:String(body.badge??old.badge??'').trim(),description:String(body.description??old.description??'').trim(),image:images[0],images,status:['sold','available'].includes(String(body.status??old.status))?String(body.status??old.status):'available'};return p}
function fail(res,e){console.error(e);return res.status(500).json({error:e.message||'حدث خطأ في الخادم.'})}
app.get(['/api/health','/health'],(req,res)=>res.json({ok:true,service:'Automobile Elkheshen API'}));
app.get(['/api/products','/products'],async(req,res)=>{try{res.json(await readProducts())}catch(e){fail(res,e)}});
app.get(['/api/admin/products','/admin/products'],auth,async(req,res)=>{try{res.json(await readProducts())}catch(e){fail(res,e)}});
app.post(['/api/admin/upload-images','/admin/upload-images'],auth,upload.array('images',12),async(req,res)=>{try{const files=req.files||[];if(!files.length)return res.status(400).json({error:'اختر صورة واحدة على الأقل.'});const allowed=['image/jpeg','image/png','image/webp','image/gif'];if(files.some(f=>!allowed.includes(f.mimetype)))return res.status(400).json({error:'مسموح فقط JPG وPNG وWEBP وGIF.'});if(files.reduce((n,f)=>n+f.size,0)>4*1024*1024)return res.status(400).json({error:'إجمالي الصور في الرفع الواحد يجب ألا يتجاوز 4 ميجابايت.'});const urls=[];for(const f of files)urls.push(await uploadGithub(f));res.json({ok:true,urls})}catch(e){fail(res,e)}});
app.post(['/api/admin/products','/admin/products'],auth,async(req,res)=>{try{const list=await readProducts();const p=cleanProduct(req.body);const i=list.findIndex(x=>x.id===p.id);if(i>=0)list[i]=p;else list.push(p);await writeProducts(list,i>=0?`Update car ${p.id}`:`Add car ${p.id}`);res.json({ok:true,product:p})}catch(e){fail(res,e)}});
app.delete(['/api/admin/products/:id','/admin/products/:id'],auth,async(req,res)=>{try{const list=await readProducts();const next=list.filter(p=>p.id!==req.params.id);if(next.length===list.length)return res.status(404).json({error:'السيارة غير موجودة.'});await writeProducts(next,`Delete car ${req.params.id}`);res.json({ok:true})}catch(e){fail(res,e)}});
app.post(['/api/order','/order'],async(req,res)=>res.json({ok:true,orderId:`ELK-${Date.now().toString().slice(-8)}`}));
module.exports=app;
